export const scores = {
  aspek_penilaian_1: {
    mahasiswa1: 1,
    mahasiswa2: 1,
    mahasiswa3: 1,
    mahasiswa4: 1,
    mahasiswa5: 1,
    mahasiswa6: 1,
    mahasiswa7: 1,
    mahasiswa8: 1,
    mahasiswa9: 1,
    mahasiswa10: 1,
  },
  aspek_penilaian_2: {
    mahasiswa1: 1,
    mahasiswa2: 1,
    mahasiswa3: 1,
    mahasiswa4: 1,
    mahasiswa5: 1,
    mahasiswa6: 1,
    mahasiswa7: 1,
    mahasiswa8: 1,
    mahasiswa9: 1,
    mahasiswa10: 1,
  },
  aspek_penilaian_3: {
    mahasiswa1: 1,
    mahasiswa2: 1,
    mahasiswa3: 1,
    mahasiswa4: 1,
    mahasiswa5: 1,
    mahasiswa6: 1,
    mahasiswa7: 1,
    mahasiswa8: 1,
    mahasiswa9: 1,
    mahasiswa10: 1,
  },
  aspek_penilaian_4: {
    mahasiswa1: 1,
    mahasiswa2: 1,
    mahasiswa3: 1,
    mahasiswa4: 1,
    mahasiswa5: 1,
    mahasiswa6: 1,
    mahasiswa7: 1,
    mahasiswa8: 1,
    mahasiswa9: 1,
    mahasiswa10: 1,
  },
};
